version: '3'
services:
  app:
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      - DATASOURCE=jdbc:mysql://db:3306/db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"